# PostHog ETL Cloud Build Configuration
# Builds Docker image and pushes to Container Registry with SHA and :latest tags
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/posthog-etl:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/posthog-etl:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - |
        gcloud container images add-tag gcr.io/$PROJECT_ID/posthog-etl:$SHORT_SHA gcr.io/$PROJECT_ID/posthog-etl:latest --quiet

  # Deploy to Cloud Run (branch-specific)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - |
        if [ "$BRANCH_NAME" = "main" ]; then
          echo "Deploying to PRODUCTION environment..."
          gcloud run deploy posthog-etl \
            --image=gcr.io/$PROJECT_ID/posthog-etl:latest \
            --region=us-central1 \
            --platform=managed \
            --service-account=etl-runner@$PROJECT_ID.iam.gserviceaccount.com \
            --memory=2Gi \
            --cpu=2 \
            --max-instances=1 \
            --concurrency=1 \
            --timeout=3600 \
            --set-env-vars=GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID,POSTHOG_DATASET_ID=posthog_etl,FIREBASE_DATASET_ID=firebase_etl_prod,POSTHOG_AGGREGATED_DATASET_ID=posthog_aggregated_prod,BIGQUERY_SECRET_NAME=bigquery-key \
            --no-allow-unauthenticated \
            --quiet
        elif [ "$BRANCH_NAME" = "dev" ]; then
          echo "Deploying to DEV environment..."
          gcloud run deploy posthog-etl-dev \
            --image=gcr.io/$PROJECT_ID/posthog-etl:latest \
            --region=us-central1 \
            --platform=managed \
            --service-account=etl-runner@$PROJECT_ID.iam.gserviceaccount.com \
            --memory=2Gi \
            --cpu=2 \
            --max-instances=1 \
            --concurrency=1 \
            --timeout=3600 \
            --set-env-vars=GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID,POSTHOG_DATASET_ID=posthog_etl,FIREBASE_DATASET_ID=firebase_etl_prod,POSTHOG_AGGREGATED_DATASET_ID=posthog_aggregated_dev,BIGQUERY_SECRET_NAME=bigquery-key \
            --no-allow-unauthenticated \
            --quiet
        else
          echo "Skipping deployment - not on main or dev branch (current: $BRANCH_NAME)"
        fi

images:
  - 'gcr.io/$PROJECT_ID/posthog-etl:$SHORT_SHA'