# PostHog ETL Cloud Build Configuration
# Builds Docker image and pushes to Container Registry with SHA and :latest tags
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/posthog-etl:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/posthog-etl:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - |
        gcloud container images add-tag gcr.io/$PROJECT_ID/posthog-etl:$SHORT_SHA gcr.io/$PROJECT_ID/posthog-etl:latest --quiet

images:
  - 'gcr.io/$PROJECT_ID/posthog-etl:$SHORT_SHA'